# Generated by Django 4.2.1 on 2023-05-22 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'categorias de servicios',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=1000)),
                ('direccion', models.TextField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.categoria')),
            ],
            options={
                'verbose_name': 'servicios a realizar',
                'verbose_name_plural': 'servicios',
                'db_table': 'Servicio',
            },
        ),
    ]
